//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "buttons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub first_attempt: i32,
    pub second_attempt: i32,
    pub third_attempt: i32,
    pub wrong: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
