//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::buttons::Entity as Buttons;
pub use super::flags::Entity as Flags;
pub use super::rel_buttons_stats::Entity as ButonsRelation;
pub use super::rel_flags_stats::Entity as FlagsRelation;
pub use super::rel_users_stats::Entity as UsersRelaton;
pub use super::stats::Entity as Stats;
pub use super::users::Entity as Users;
