//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rel-flags-stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub stats_id: i32,
    pub flags_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::flags::Entity",
        from = "Column::FlagsId",
        to = "super::flags::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Flags,
    #[sea_orm(
        belongs_to = "super::stats::Entity",
        from = "Column::StatsId",
        to = "super::stats::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Stats,
}

impl Related<super::flags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Flags.def()
    }
}

impl Related<super::stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
