//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "rel-users-stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub stats_id: i32,
    pub users_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stats::Entity",
        from = "Column::StatsId",
        to = "super::stats::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Stats,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UsersId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stats.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
