//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stats")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::rel_buttons_stats::Entity")]
    RelButtonsStats,
    #[sea_orm(has_many = "super::rel_flags_stats::Entity")]
    RelFlagsStats,
    #[sea_orm(has_many = "super::rel_users_stats::Entity")]
    RelUsersStats,
}

impl Related<super::rel_buttons_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelButtonsStats.def()
    }
}

impl Related<super::rel_flags_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelFlagsStats.def()
    }
}

impl Related<super::rel_users_stats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelUsersStats.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
